# ==========================================
# 多币种跨市场套利机器人配置文件
# ==========================================

# ------------------------------------------
# 交易所设置
# 注意: 当前版本为模拟交易版本，API密钥不会被实际使用
# ------------------------------------------
exchanges:
  # OKX交易所配置
  okx:
    name: "OKX"                            # 交易所名称
    api_key: "YOUR_OKX_API_KEY"           # API密钥 (模拟版本中不使用)
    secret: "YOUR_OKX_SECRET"             # API密钥密文 (模拟版本中不使用)
    password: "YOUR_OKX_PASSWORD"         # API密码 (OKX必需，模拟版本中不使用)
    testnet: true                         # 是否使用测试网络 (true=测试网络, false=主网络)
  
  # XT交易所配置
  xt:
    name: "XT"                            # 交易所名称
    api_key: "YOUR_XT_API_KEY"            # API密钥 (模拟版本中不使用)
    secret: "YOUR_XT_SECRET"              # API密钥密文 (模拟版本中不使用)
    testnet: true                         # 是否使用测试网络 (true=测试网络, false=主网络)

# ------------------------------------------
# 交易参数设置
# ------------------------------------------
trading:
  # 默认交易对 (当动态检测失败时使用)
  symbol: "BTC/USDT"
  
  # 手续费设置 (以小数表示，0.1% = 0.001)
  okx_fee: 0.0005                         # OKX手续费 (0.05%)
  xt_fee: 0.0005                          # XT手续费 (0.05%)
  
  # 最小利润阈值 (以小数表示)
  min_profit_threshold: 0.001             # 最小利润阈值 (0.1%)
  
  # 最大持仓时间 (秒)
  max_exposure_time: 5                    # 最大持仓时间 (5秒)
  
  # 仓位大小设置 (占总资金的百分比)
  position_size_percent: 0.1              # 仓位大小 (10% of capital)
  
  # 支持的交易对列表
  # 系统会自动检测交易所支持的交易对，并选择共同支持的交易对
  supported_pairs:
    - "BTC/USDT"                          # 比特币/USDT
    - "ETH/USDT"                          # 以太坊/USDT
    - "BNB/USDT"                          # 币安币/USDT
    - "ADA/USDT"                          # ADA/USDT
    - "DOT/USDT"                          # DOT/USDT

# ------------------------------------------
# 模拟交易设置
# ------------------------------------------
simulation:
  initial_capital: 10000                  # 初始资金 (USDT)
  mode: "simulation"                      # 运行模式 ("simulation"=模拟交易, "live"=实盘交易)

# ------------------------------------------
# 日志设置
# ------------------------------------------
logging:
  level: "INFO"                           # 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "logs/arbitrage_bot.log"          # 日志文件路径

# ==========================================
# 配置说明:
# 1. 当前版本为模拟交易版本，所有API密钥字段仅为占位符
# 2. 修改配置后请重启程序使更改生效
# 3. 日志文件将记录所有交易活动和系统信息
# 4. 支持的交易对会自动检测，此处为默认列表
# ==========================================